# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [12]:
# 1. 把整个 GitHub 仓库克隆到 Colab 云端
!git clone https://github.com/rougier/numpy-100.git

# 2. 进入克隆下来的文件夹
%cd numpy-100

Cloning into 'numpy-100'...
remote: Enumerating objects: 1124, done.
remote: Counting objects: 100% (518/518), done.
remote: Compressing objects: 100% (119/119), done.
remote: Total 1124 (delta 461), reused 403 (delta 399), pack-reused 606 (from 2)
Receiving objects: 100% (1124/1124), 519.00 KiB | 11.04 MiB/s, done.
Resolving deltas: 100% (658/658), done.
/content/numpy-100/numpy-100


In [13]:
# 安装缺失的依赖库
!pip install mdutils nbformat

In [14]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
np.show_config()

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
Z=np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
Z=np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
import numpy as np
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
Z=np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
Z=np.arange(50)
Z_rev=Z[::-1]
print(Z_rev)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
Z=np.arange(9)
Z=Z.reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
Z=np.array([1,2,0,0,4,0])
mask=(Z!=0)
indices=np.where(mask)
print(indices)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
Z=np.eye(3,3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
Z=np.random.random((3,3,3))
print(Z)

[[[0.68747839 0.37581157 0.31738469]
  [0.54862882 0.28645381 0.06320192]
  [0.82309685 0.47654497 0.19664852]]

 [[0.05550033 0.57632181 0.51188858]
  [0.38611627 0.79001477 0.9101076 ]
  [0.29658586 0.26452474 0.69487033]]

 [[0.06439015 0.71611083 0.57102011]
  [0.32892098 0.32866981 0.70063915]
  [0.25418469 0.45439655 0.38430513]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
Z=np.random.random((10,10))
print(Z.min(),Z.max())

0.015282104310215483 0.990757265240747


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
Z=np.random.random(30)
print(Z.mean())

0.5087207246521255


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
Z=np.ones((10,10))
Z[1:-1,1:-1]=0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
Z=np.random.random((10,10))
Z=np.pad(Z,pad_width=1,mode='constant',constant_values=0)
print(Z)

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.04993443 0.65956411 0.64273473 0.70637911 0.35174737
  0.24595135 0.97271435 0.19973563 0.18565448 0.33222819 0.        ]
 [0.         0.53281171 0.92332913 0.4523283  0.15859596 0.22086841
  0.81465687 0.18012669 0.90439937 0.10669764 0.52672125 0.        ]
 [0.         0.76287581 0.82956866 0.17640976 0.89090223 0.47603716
  0.75275047 0.70556059 0.85833539 0.74376658 0.60131225 0.        ]
 [0.         0.39828393 0.31679351 0.20122205 0.57187266 0.71503322
  0.43909668 0.86824512 0.79183346 0.36886887 0.31556496 0.        ]
 [0.         0.21856385 0.37175504 0.9982701  0.05215163 0.83658385
  0.9733718  0.67636419 0.68240251 0.99104779 0.32526378 0.        ]
 [0.         0.53671972 0.93664226 0.28738131 0.05555447 0.60179922
  0.14862421 0.72473632 0.74281194 0.96306203 0.36416711 0.        ]
 [0.         0.31998101 0.46116867 0.55469337 0.7

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
Z=np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
Z=np.zeros((8,8))
Z[0::2,1::2]=1
Z[1::2,0::2]=1
print(Z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
print(np.unravel_index(99,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
Z=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
Z=np.random.random((5,5))
Z=(Z-Z.mean())/(Z.std())
print(Z)

[[-1.37059841  0.62426779  0.6729406   0.67790073 -1.3848464 ]
 [-1.10123605 -0.10981721  1.42076295 -0.85879215 -0.84140866]
 [ 0.83401545  0.31641385  1.05134312 -0.8121972  -0.76470152]
 [ 1.59013922 -0.53344672  1.2248458  -1.24083373 -1.46225393]
 [ 1.38653924 -0.52846944  0.19591276  1.31986582 -0.3063459 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color_type=np.dtype([('r',np.ubyte),('g',np.ubyte),('b',np.ubyte),('a',np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
A=np.random.random((5,3))
B=np.random.random((3,2))
C=np.matmul(A,B)
D=A@B
print(A)
print(B)
print(C)
print(D)

[[0.03975082 0.71006299 0.20516341]
 [0.83123516 0.76312533 0.8571258 ]
 [0.42699045 0.51627324 0.25358789]
 [0.65871348 0.64248473 0.10159352]
 [0.66682319 0.71341325 0.9337148 ]]
[[0.77956085 0.39313859]
 [0.76690984 0.25841104]
 [0.07323039 0.48926246]]
[[0.59056667 0.29949445]
 [1.29601437 0.94335011]
 [0.7473704  0.42534817]
 [1.01367483 0.47469674]
 [1.13532919 0.90333939]]
[[0.59056667 0.29949445]
 [1.29601437 0.94335011]
 [0.7473704  0.42534817]
 [1.01367483 0.47469674]
 [1.13532919 0.90333939]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
Z=np.arange(11)
Z[(Z>3)&(Z<8)]*=-1
print(Z)
np.where((Z>3)&(Z<8),Z*-1,Z)
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [15]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [16]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipykernel_1119/3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_1119/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipykernel_1119/3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
Z=np.random.uniform(-10,10,10)
print(Z)
Z=np.copysign(np.ceil(abs(Z)),Z)
print(Z)

[-9.44559642  2.22105697  0.9457568   9.60687373  2.56433139  6.81075184
  5.75396799  1.02553219  3.76928387 -1.86589988]
[-10.   3.   1.  10.   3.   7.   6.   2.   4.  -2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
Z1=np.random.randint(0,10,10)
Z2=np.random.randint(0,10,10)
print(Z1)
print(Z2)
res=np.intersect1d(Z1,Z2)
print(res)

[1 6 4 6 5 8 5 3 1 5]
[5 3 7 2 8 1 6 6 0 0]
[1 3 5 6 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
with np.errstate(all="ignore"):
  np.arange(3)/0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1)==np.emath.sqrt(-1))

False


/tmp/ipykernel_426/3643901316.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1)==np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
yesterday=np.datetime64('today')-np.timedelta64(1)
today=np.datetime64('today')
tomorrow=np.datetime64('today')+np.timedelta64(1)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
Z=np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A=np.ones(3)*1
B=np.ones(3)*2
print(A)
print(B)
np.add(A,B,out=B)
np.negative(A,out=A)
np.divide(A,2,out=A)
np.multiply(A,B,out=A)
print(A)

[1. 1. 1.]
[2. 2. 2.]
[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
Z=np.random.uniform(0,10,10)
Z1=Z-Z%1
Z2=Z//1
Z3=np.floor(Z)
Z4=Z.astype('int')
Z5=np.trunc(Z)
print(Z)
print(Z1)
print(Z2)
print(Z3)
print(Z4)
print(Z5)

[0.06901111 0.31525743 9.23752206 8.31530197 3.44250845 3.35752114
 7.24475189 6.79780555 9.56422605 7.77095973]
[0. 0. 9. 8. 3. 3. 7. 6. 9. 7.]
[0. 0. 9. 8. 3. 3. 7. 6. 9. 7.]
[0. 0. 9. 8. 3. 3. 7. 6. 9. 7.]
[0 0 9 8 3 3 7 6 9 7]
[0. 0. 9. 8. 3. 3. 7. 6. 9. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [20]:
Z=np.zeros((5,5))
Z+=np.arange(5)
print(Z)
Z=np.tile(np.arange(5),(5,1))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [21]:
def generator():
  for _ in range(10):
    yield _
Z=np.fromiter(generator(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [23]:
Z=np.linspace(0,1,11,endpoint=False)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [26]:
Z=np.random.random(10)
print(Z)
Z.sort()
print(Z)

[0.86039192 0.9440149  0.57793779 0.75684361 0.03893261 0.03451164
 0.56345674 0.30466302 0.98723281 0.36277077]
[0.03451164 0.03893261 0.30466302 0.36277077 0.56345674 0.57793779
 0.75684361 0.86039192 0.9440149  0.98723281]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [28]:
Z=np.random.random(10)
np.add.reduce(Z)

np.float64(6.239372032512763)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [47]:
A=np.random.randint(0,2,5)
B=np.random.randint(0,2,5)
print(A)
print(B)
print(np.allclose(A,B))
print(np.array_equal(A,B))

[0 1 1 1 1]
[0 1 1 1 1]
True
True


#### 43. Make an array immutable (read-only) (★★☆)

In [48]:
Z=np.zeros(10)
Z.flags.writeable=False
Z[0]=1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [54]:
Z=np.random.random((10,2))
X,Y=Z[:,0],Z[:,1]
R=np.sqrt(X**2+Y**2)
T=np.arctan2(Y,X)
print(R)
print(T)
polar_coord=np.column_stack((R,T))
print(polar_coord)
polar_coord=np.stack((R,T),axis=1)
print(polar_coord)

[0.74968331 0.24744412 0.97111122 0.81737986 0.46327981 0.27870659
 0.67884967 0.98527372 1.00263266 0.98039198]
[1.16975515 1.44938767 1.3812171  0.73757167 0.61093918 0.99286356
 1.050184   1.37208299 0.23179864 0.45953742]
[[0.74968331 1.16975515]
 [0.24744412 1.44938767]
 [0.97111122 1.3812171 ]
 [0.81737986 0.73757167]
 [0.46327981 0.61093918]
 [0.27870659 0.99286356]
 [0.67884967 1.050184  ]
 [0.98527372 1.37208299]
 [1.00263266 0.23179864]
 [0.98039198 0.45953742]]
[[0.74968331 1.16975515]
 [0.24744412 1.44938767]
 [0.97111122 1.3812171 ]
 [0.81737986 0.73757167]
 [0.46327981 0.61093918]
 [0.27870659 0.99286356]
 [0.67884967 1.050184  ]
 [0.98527372 1.37208299]
 [1.00263266 0.23179864]
 [0.98039198 0.45953742]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [57]:
Z=np.random.random(10)
print(Z)
Z_max=Z.max()
Z=np.where(Z==Z_max,0,Z)
print(Z)
Z[Z==Z.max()]=0
print(Z)


Z=np.random.random(10)
print(Z)
Z[Z.argmax()]=0
print(Z)

[0.11107051 0.09159824 0.44284428 0.08138452 0.96695679 0.54980484
 0.76723923 0.25391432 0.66806208 0.27133324]
[0.11107051 0.09159824 0.44284428 0.08138452 0.         0.54980484
 0.76723923 0.25391432 0.66806208 0.27133324]
[0.11107051 0.09159824 0.44284428 0.08138452 0.         0.54980484
 0.         0.25391432 0.66806208 0.27133324]
[0.62106346 0.47672155 0.14997102 0.3460948  0.69780966 0.49674655
 0.67272386 0.73520511 0.09884578 0.80615799]
[0.62106346 0.47672155 0.14997102 0.3460948  0.69780966 0.49674655
 0.67272386 0.73520511 0.09884578 0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [58]:
Z=np.zeros((5,5),[('x',float),('y',float)])
Z['x'],Z['y']=np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)